export const eBookData = [
    {
        id: 'c44jd',
        title: 'After The Crash ',
        description: 'A story on who is the father and who is the son',
        durationInHours:7,
        durationInMinutes:12,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1423327111i/24862192.jpg",
        authorName:"Michael Bussi",
        narratorName:"Boran Mark",
        summary:"This book is about taking strong decisions in life. It is a must read for everyone who wants to be successful in life.",
        releaseDate:"07 May, 2012",
        language:"English",
        publisher:"Corpo Inc",
        rating:12315,
        colorCode:'fff',
        categories:"Romance",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'aewrb2',
        title: 'Aikido Student Manual',
        description: 'Learn how to take strong decisions in life',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://m.media-amazon.com/images/I/41OX6CyPlLL._SL500_.jpg",
        authorName:"James Kora",
        narratorName:"Boran Mark",
        summary:"This book is about learning aikido and its life. It is a must read for everyone who wants to know the story of Aikido.",
        releaseDate:"12 Apr, 2016",
        language:"English",
        publisher:"Corpo Inc",
        rating:52356,
        colorCode:'E34A24',
        categories:"Comedy",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'a1b2',
        title: 'Looney Tunes',
        description: 'Learn how to take strong decisions in life',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://i1.sndcdn.com/artworks-3SD8lFMYlkD5znic-CRqlTw-t500x500.jpg",
        authorName:"James Kora",
        narratorName:"Boran Mark",
        summary:"This book is about the tales of looney tunes. It is a must read for everyone who wants to know the story of looney tunes.",
        releaseDate:"18 Oct, 2021",
        language:"English",
        publisher:"Corpo Inc",
        rating:12356,
        colorCode:'CABF1D',
        categories:"Education",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'lofn02',
        title: 'Pride and Prejudice',
        description: 'Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813.',
        durationInHours:8,
        durationInMinutes:12,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg",
        authorName:"Jane Austen",
        narratorName:"Jane Austen",       
        summary:"Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work and its vivacious heroine, Elizabeth Bennet",
        releaseDate:"12 Mar, 2005",
        language:"English",
        publisher:"Semmo Inc",
        rating:7955,
        colorCode:'FFFFFF',
        categories:"Romance",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'aam7c2',
        title: '1984',
        description: '1984 is a dystopian social science fiction novel by English novelist George Orwell.',
        durationInHours:2,
        durationInMinutes:21,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1532714506i/40961427.jpg",
        authorName:"George Orwel",
        narratorName:"George Orwel",
        summary:"Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Comedy",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'alrp12',
        title: 'Crime and Punishment',
        description: 'Crime and Punishment is a novel by the Russian author Fyodor Dostoevsky.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1382846449i/7144.jpg",
        authorName:"Fyodor Dostoevsky",
        narratorName:"Fyodor Dostoevsky",
        summary:"Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret.",
        releaseDate:"07 Jun, 2012",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Education",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'aloz32',
        title: 'Hamlet',
        description: 'Hamlet is a novel by William Shakespeare',
        durationInHours:2,
        durationInMinutes:12,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1351051208i/1420.jpg",
        authorName:"William Shakespeare",
        narratorName:"William Shakespeare",
        summary:"Among Shakespeare's plays, Hamlet is considered by many his masterpiece. Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career. ",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:6185,
        colorCode:'DDDCCF',
        categories:"Romance",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'zikn90',
        title: 'One Hundred Years of Solitude',
        description: 'One Hundred Years of Solitude is a novel by Colombian author Gabriel García Márquez.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320.jpg",
        authorName:"Gabriel García Márquez",
        narratorName:"Gabriel García Márquez",
        summary:"The brilliant, bestselling, landmark novel that tells the story of the Buendia family, and chronicles the irreconcilable conflict between the desire for solitude ",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Comedy",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'aqwe62',
        title: 'The Odyssey',
        description: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1711957706i/1381.jpg",
        authorName:"Homer",
        narratorName:"Homer",
        summary:"Sing to me of the man, Muse, the man of twists and turns driven time and again off course, once he had plundered the hallowed heights of Troy.",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Education",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'ghgh45',
        title: 'The Stranger',
        description: ' The Stranger is a novel by Albert Camus, published in 1942.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1590930002i/49552.jpg",
        authorName:"Albert Camus",
        narratorName:"Albert Camus",
        summary:"Published in 1942 by French author Albert Camus, The Stranger has long been considered a classic of twentieth-century literature. Le Monde ranks it as number one on its 100 Books of the Century list. ",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Romance",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'sdre13',
        title: 'The Brothers Karamazov',
        description: 'The Brothers Karamazov is a novel by',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1427728126i/4934.jpg",
        authorName:"Fyodor Dostoevsky",
        narratorName:"Fyodor Dostoevsky",
        summary:"The Brothers Karamazov is a murder mystery, a courtroom drama, and an exploration of erotic rivalry in a series of triangular love affairs involving the wicked and sentimental Fyodor Pavlovich Karamazov and his three sons―the impulsive and sensual Dmitri; the coldly rational Ivan; and the healthy, red-cheeked young novice Alyosha. ",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Comedy",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'plmnj00',
        title: 'Great Expectations',
        description: ' Great Expectations is a novel by Charles Dickens ',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631687432i/2623.jpg",
        authorName:"Charles Dickens",
        narratorName:"Charles Dickens",
        summary:"Great Expectations charts the progress of Pip from childhood through often painful experiences to adulthood, as he moves from the Kent marshes to busy, commercial London, encountering a variety of extraordinary characters.",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Education",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'zxas22',
        title: 'The Old Man and the Sea',
        description: 'The old man and the sea is a novel by Ernest Hemingway.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329189714i/2165.jpg",
        authorName:"Ernest Hemingway",
        narratorName:"Ernest Hemingway",
        summary:"This short novel, already a modern classic, is the superbly told, tragic story of a Cuban fisherman in the Gulf Stream and the giant Marlin he kills and loses—specifically referred to in the citation accompanying the author's Nobel Prize for literature in 1954.",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Romance",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'tyty88',
        title: 'King Lear',
        description: 'King Lear is a tragedy written by William Shakespeare.',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1331563731i/12938.jpg",
        authorName:"William Shakespeare",
        narratorName:"William Shakespeare",
        summary:"Shakespeare’s King Lear challenges us with the magnitude, intensity, and sheer duration of the pain that it represents. Its figures harden their hearts, engage in violence, or try to alleviate the suffering of others.",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Comedy",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    {
        id: 'uquy34',
        title: 'The Canterbury Tales',
        description: 'Learn how to take strong decisions in life',
        durationInHours:1,
        durationInMinutes:17,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1261208589i/2696.jpg",
        authorName:"Geoffrey Chaucer",
        narratorName:"Geoffrey Chaucer",
        summary:"The procession that crosses Chaucer's pages is as full of life and as richly textured as a medieval tapestry. The Knight, the Miller, the Friar, the Squire, the Prioress, the Wife of Bath, and others who make up the cast of characters",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF',
        categories:"Education",
        sampleAudio:'https://safari-books-mobile.s3.ap-south-1.amazonaws.com/clwymbela0001coko5h4b0mar/k0qx5lmfuobzvuk5nt1xapcw/verificationfiles/compress.mp3'
    },
    

]
