export const eBookData = [
    {
        id: 'c44jd',
        title: 'After The Crash ',
        description: 'A story on who is the father and who is the son',
        durationInHours:7,
        durationInMinutes:12,
        coverImage:"https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1423327111i/24862192.jpg",
        authorName:"Michael Bussi",
        narratorName:"Boran Mark",
        summary:"This book is about taking strong decisions in life. It is a must read for everyone who wants to be successful in life.",
        releaseDate:"07 May, 2012",
        language:"English",
        publisher:"Corpo Inc",
        rating:12315,
        colorCode:'fff'
    },
    {
        id: 'aewrb2',
        title: 'Aikido Student Manual',
        description: 'Learn how to take strong decisions in life',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://m.media-amazon.com/images/I/41OX6CyPlLL._SL500_.jpg",
        authorName:"James Kora",
        narratorName:"Boran Mark",
        summary:"This book is about taking strong decisions in life. It is a must read for everyone who wants to be successful in life.",
        releaseDate:"12 Apr, 2016",
        language:"English",
        publisher:"Corpo Inc",
        rating:52356,
        colorCode:'E34A24'
    },
    {
        id: 'a1b2',
        title: 'Looney Tunes',
        description: 'Learn how to take strong decisions in life',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://i1.sndcdn.com/artworks-3SD8lFMYlkD5znic-CRqlTw-t500x500.jpg",
        authorName:"James Kora",
        narratorName:"Boran Mark",
        summary:"This book is about taking strong decisions in life. It is a must read for everyone who wants to be successful in life.",
        releaseDate:"18 Oct, 2021",
        language:"English",
        publisher:"Corpo Inc",
        rating:12356,
        colorCode:'CABF1D'
    },
    {
        id: 'aafn82',
        title: 'The art of taking strong decisions in life',
        description: 'Learn how to take strong decisions in life',
        durationInHours:4,
        durationInMinutes:37,
        coverImage:"https://blog.kotobee.com/wp-content/uploads/2019/03/red-book-rests-on-wood670.jpg",
        authorName:"James Kora",
        narratorName:"Boran Mark",
        summary:"This book is about taking strong decisions in life. It is a must read for everyone who wants to be successful in life.",
        releaseDate:"07 Jan, 2003",
        language:"English",
        publisher:"Corpo Inc",
        rating:385,
        colorCode:'DDDCCF'
    },
    

]
